apiVersion: apps/v1
kind: Deployment
metadata:
  name: nodes-todo-deployment
  labels:
    app: nodes-todo
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nodes-todo
  template:
    metadata:
      labels:
        app: nodes-todo
    spec:
      containers:
      - name: nodes-todo
        image: rabi4450/nodes-app:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nodes-todo
  labels:
    app: nodes-todo
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  selector:
    app: nodes-todo
  type: NodePort

